name: main-push
on:
  pull_request:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    if: github.event.pull_request.merged == true
    environment:
      name: xivart
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: true
          PRERELEASE: true
          RELEASE_BRANCHES: test
          VERBOSE: true
          INITIAL_VERSION: 0.0.0
          DEFAULT_BUMP: patch
      - name: version-tag-major
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git fetch --tags
          tagFmt="^v?[0-9]+\.[0-9]+\.[0-9]+$"
          tag="$(git for-each-ref --sort=-v:refname --format '%(refname:lstrip=2)' | grep -E "$tagFmt" | head -n 1)"
          major=${tag%%.*}
          git tag -f "$major"
          git push -f origin "$major"

